#!/usr/bin/env python

import os
import pty
import threading
import argparse
import subprocess
import shutil
import logging
import sys
from serial import Serial
from serial_expect import serial_expect
import time
from netbooter_control import netbooter_control

from pathlib import Path
from datetime import datetime

#from ddrctrl_experiment import create_log_path, setup_logger, initial_experiment_logging, create_base_filename_identifier, create_base_filename
from new_experiment_machine import ExperimentState, NewExperiment

from litex.tools.litex_term import LiteXTerm

from rowhammer_tester.scripts.utils import RemoteClient, litex_server, read_ident

# Format string for printing the date and time
TIME_STRING_FORMAT = "%Y-%m-%d %H:%M:%S"
DEFAULT_LITEX_LOGIN_DELAY = 15
DEFAULT_NETBOOTER_PORT = 5

DEFAULT_BIST_PATTERN = "0x5a5a5a5a"
INITIAL_STARTING_STATE = "Initial Starting State"
REPOWER_BOARD_STATE = "Repower Board State"
START_SERVER_STATE = "Start Server State"
CREATE_CLIENT_STATE = "Create Client State"
INITIAL_PROMPT_STATE = "Initial Prompt State"
MEM_INIT_STATE = "Mem Init State"
MEM_COMPARE_STATE = "Mem Compare State"
TERMINATING_STATE = "Terminating State"


def pty2crossover(wb, m, stop):
    ''' Run as a thread '''
    while not stop.is_set():
        r = os.read(m, 1)
        wb.regs.uart_xover_rxtx.write(ord(r))


def crossover2pty(wb, m, stop):
    ''' Run as a thread '''
    while not stop.is_set():
        if wb.regs.uart_xover_rxempty.read() == 0:
            r = wb.regs.uart_xover_rxtx.read()
            os.write(m, bytes(chr(r).encode("utf-8")))

def create_base_filename_identifier(prefix):
    ''' Create a base filename used for all files generated by this experiment '''
    current_date_time = datetime.now().strftime("%B_%d_%Y__%H_%M_%S")
    # Add CTRL as the prefix to specify it is a DDR controller test
    #  (the bistream is not enough - the same bitstream may be used for the DDR test)
    return str(prefix +  "_" + current_date_time)

def setup_logger(log_filename:str, include_level = True, print_stdout = False):
    ''' Static method for creating custom loggers '''
    if include_level:
        formatter = logging.Formatter('[%(asctime)s] %(levelname)-8s %(message)s', datefmt=TIME_STRING_FORMAT)
    else:
        formatter = logging.Formatter('[%(asctime)s] %(message)s', datefmt=TIME_STRING_FORMAT)
    try:
        handler = logging.FileHandler(log_filename)
    except (FileNotFoundError) as error:
        print("Logging File "+log_filename+"cannot be opened")
        return None

    handler.setFormatter(formatter)
    logger = logging.getLogger("main_log")
    logger.setLevel(logging.INFO)
    logger.addHandler(handler)

    if print_stdout:
        consoleHandler = logging.StreamHandler(sys.stdout)
        consoleHandler.setFormatter(formatter)
        logger.addHandler(consoleHandler)

    return logger

def create_log_path(prefix,basename,path_dir=None,prefix_first=False):
    ''' Creates a Path to a log file'''

    if prefix_first:
        filename = str(prefix+"_"+basename+".log")
    else:
        filename = str(basename+"_"+prefix+".log")

    if path_dir:
        filepath = Path(path_dir , filename)
    else:
        filepath = filename
    return filepath

def expect_prompt(expect, number_of_enters=1,expect_timeout=DEFAULT_LITEX_LOGIN_DELAY):
    ''' Send "Enter" and expects the "litex" prompt (does this once)
        Does NOT set state (state actions should set state)
        Returns True if expect was successful, False otherwise
          Calling functions should query for details about failed expect
    '''

    LITEX_LOGIN_PATTERN = "^.*litex[^>]*> "
    for i in range(number_of_enters):
        expect.sendline("\n")
    expect.expect(LITEX_LOGIN_PATTERN,timeout=expect_timeout)
    if expect.has_error():
        return False
    return True

def retry_expect_prompt(ex, number_of_enters=1,expect_retries = 0, expect_timeout=DEFAULT_LITEX_LOGIN_DELAY):
    MAX_TRIES = expect_retries + 1
    success = False
    try_num = 0
    while not success:
        ex.logger.info(f"Expect prompt attempt #{try_num+1}")
        expect_result = expect_prompt(ex.expect,number_of_enters=number_of_enters)
        if not expect_result:
            if try_num >= MAX_TRIES:
                ex.logger.error("Maximum number of tries: exiting")
                return False
            time.sleep(15)
            try_num += 1
        else:
            success = True
    ex.logger.info("Login prompt success")
    return True

def initial_starting_state_actions(ex):
    '''
    '''
    #return INITIAL_PROMPT_STATE
    return REPOWER_BOARD_STATE

def repower_board_state_actions(ex):
    '''
    '''

    # Make sure netbooter is accessible
    netbooter_ip = ex.args.netbooter_ip
    ex.netbooter = netbooter_control(netbooter_ip,ex.logger)
    if not ex.netbooter.ping_netbooter():
        ex.logger.error("Netbooter not on network")
        return TERMINATING_STATE

    # Repower the board
    ex.netbooter.turn_off_port(ex.args.netbooter_port)
    ex.netbooter.turn_on_port(ex.args.netbooter_port)

    return START_SERVER_STATE

def start_server_state_actions(ex):
    '''
    '''
    post_boot_wait_time = 15
    post_server_wait_time = 15
    # Wait a bit for system to boot up
    ex.logger.info(f"Giving time for system to boot ({post_boot_wait_time} seconds)")
    time.sleep(post_boot_wait_time)
    ex.logger.info("Starting Litex Server")
    try:
        litex_server()
    except (Exception) as error:
        print(str(error))
        return TERMINATING_STATE
    ex.logger.info(f"Giving time for server to start ({post_server_wait_time} seconds)")
    time.sleep(post_server_wait_time)
    return CREATE_CLIENT_STATE

def create_client_state_actions(ex):
    '''
    '''
    wb = RemoteClient()
    wb.open()

    # Need to figure out how to get read_ident working
    #ex.logger.info("Board info:", read_ident(wb))

    m, s = pty.openpty()
    tty = os.ttyname(s)
    ex.logger.info("LiteX Crossover UART created: {}".format(tty))

    stop_event = threading.Event()
    threads = [
        threading.Thread(target=pty2crossover, args=[wb, m, stop_event], daemon=True),
        threading.Thread(target=crossover2pty, args=[wb, m, stop_event], daemon=True),
    ]
    for thread in threads:
        thread.start()

    baudrate = int(float(ex.args.baudrate))
    timout = 30
    #print('Using serial backend: {} with baudrate {}'.format(args.term,baudrate))
    ex.logger.info("Attempting to open:"+str(tty)+" at baud "+str(baudrate)+
            " with timeout=" + str(timout))

    try:
        serial_fd = Serial(tty, baudrate=baudrate, timeout=timout)
    except (Exception) as error:
        # SerialException if device cannot be found or properly configured
        # ValueError if values are incorrect
        ex.logger.error("Failed to open:"+str(tty)+" ("+str(type(error))+":"+str(error)+")")
        return TERMINATING_STATE
    ex.logger.info("Serial port "+tty+" open")

    ex.serial_fd = serial_fd

    ex.expect = serial_expect(serial_fd,ex.logger,pexpect_stdout=ex.uart_log_file, timestampformat = TIME_STRING_FORMAT)
    ex.expect.create_uart_spawn()

    return INITIAL_PROMPT_STATE

def initial_prompt_state_actions(ex):
    ''' Wait for the initial prompt
    '''
    # System has to boot up and calibrate the memory
    boot_time = 30
    send_result = ex.expect.sendline()
    ex.logger.info(f"Giving time for bios to initialize ({boot_time} seconds)")
    time.sleep(boot_time)

    MAX_TRIES = 10
    success = False
    try_num = 0
    while not success:
        ex.logger.info(f"Initial prompt attempt #{try_num+1}")
        expect_result = expect_prompt(ex.expect,number_of_enters=2)
        if not expect_result:
            if try_num >= MAX_TRIES:
                ex.logger.error("Maximum number of tries: exiting")
                return TERMINATING_STATE
            time.sleep(15)
            try_num += 1
        else:
            success = True
    ex.logger.info("Login prompt success")

    return MEM_INIT_STATE

def mem_init_state_actions(ex):
    # Run the memory initialize command
    #mem_init_cmd = f"mem_write 0x40000000 0xa5a5a5a5 0x10000000 4"
    mem_init_cmd = f"mem_write 0x40000000 {ex.args.default_bist_pattern} 0x10000000 4"
    #mem_init_cmd = f"mem_write 0x40000000 {ex.args.default_bist_pattern} 0x100 4"
    #print(mem_init_cmd)
    if ex.args.skip_mem_init:
        ex.logger.info("Skipping memory initialization")
        return MEM_COMPARE_STATE

    send_result = ex.expect.sendline(mem_init_cmd)
    mem_init_delay_time = 90
    ex.logger.info(f"Giving time for mem_write command ({mem_init_delay_time} seconds)")
    time.sleep(mem_init_delay_time)
 
    expect_result = expect_prompt(ex.expect,number_of_enters=2)
    if not expect_result:
        ex.logger.info("No response")
        return TERMINATING_STATE

    return MEM_COMPARE_STATE

def mem_compare_state_actions(ex):
    # Compare memory (takes about 2 minutes): perhaps break this up a bit so we don't have 
    #  the UART full with all the differences when there is a failure
    #mem_cmp 0x40000000 0x60000000 0x08000000
    # There are 0x40000000 bytes or 0x10000000 words
    # If we compare half the array to each other then only 
    # compare 0x08000000 words
    INIT_ADDR =          0x40000000
    COMPARE_ADDR =       0x60000000
    COMPARE_DIFF = COMPARE_ADDR - INIT_ADDR
    COMPARE_INCREMENT =     0x40000
    WORDS_TO_COMPARE =     COMPARE_INCREMENT // 4
    MAX_COMPARE =        0x08000000
    COMPARE_INFO_MESSAGE_LENGTH = 0x800000
    INTER_COMPARE_DELAY = 1.0

    total_increment = 0
    for addr in range(INIT_ADDR,COMPARE_ADDR,COMPARE_INCREMENT):
        compare_addr = addr + COMPARE_DIFF
        total_increment += COMPARE_INCREMENT
        mem_compare_cmd = f"mem_cmp 0x{addr:08X} 0x{compare_addr:08X} 0x{WORDS_TO_COMPARE:08X} 4"
        if total_increment % COMPARE_INFO_MESSAGE_LENGTH == 0:
            ex.logger.info(mem_compare_cmd)
        send_result = ex.expect.sendline(mem_compare_cmd)
        time.sleep(INTER_COMPARE_DELAY)
         #print(send_result)
        expect_result = False
        max_tries = 20
        tries = 0
        while not expect_result:
            expect_result = expect_prompt(ex.expect,number_of_enters=1)
            if not expect_result:
                tries += 1
                ex.logger.info(f"Failed expect prompt try {tries}")
                if tries >= max_tries:
                    return TERMINATING_STATE

    return MEM_COMPARE_STATE

def terminating_state_actions(ex):
    ''' Terminates experiment
        no state change
    '''
    ex.stop()
    return TERMINATING_STATE

def build_experiment(args,logger,single_step=False):
    '''
    Builds the experiment object and its related states for the experiment state machine.
    '''


    # Create a new experiment object
    experiment = NewExperiment(logger,single_step=single_step)

    # Save the arguments
    experiment.args = args
    experiment.logger = logger

    # INITIAL_STARTING_STATE
    # - Do nothing: place holder for start
    experiment.add_state(ExperimentState(
        INITIAL_STARTING_STATE,
        initial_starting_state_actions,
    ))

    experiment.add_state(ExperimentState(
        REPOWER_BOARD_STATE,
        repower_board_state_actions,
    ))

    experiment.add_state(ExperimentState(
        START_SERVER_STATE,
        start_server_state_actions,
    ))

    experiment.add_state(ExperimentState(
        CREATE_CLIENT_STATE,
        create_client_state_actions,
    ))

    experiment.add_state(ExperimentState(
        INITIAL_PROMPT_STATE,
        initial_prompt_state_actions,
    ))

    experiment.add_state(ExperimentState(
        MEM_INIT_STATE,
        mem_init_state_actions,
    ))

    experiment.add_state(ExperimentState(
        MEM_COMPARE_STATE,
        mem_compare_state_actions,
    ))

    # TERMINATING_STATE
    # - Do nothing: place holder for ending state. Will set experiment to "stop"
    # - Enter this state when the experiment cannot continue
    experiment.add_state(ExperimentState(
        TERMINATING_STATE,
        terminating_state_actions,
    ))
    return experiment

def main():

    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-b', '--baudrate', default='1e6', help='Serial baud rate')
    parser.add_argument("--default_bist_pattern", help="Pattern for memory test (i.e., 0x5a)", default = DEFAULT_BIST_PATTERN)
    parser.add_argument("--log_dir", help="Directory to store log files", type=str)
    parser.add_argument("--skip_mem_init", help="Skip memory initialization", action='store_true')
    parser.add_argument_group(netbooter_control.netbooter_group_args(parser))
    parser.add_argument("--netbooter_port", help="Netbooter Port", type=int, default = DEFAULT_NETBOOTER_PORT)
    args = parser.parse_args()

    '''
    wb = RemoteClient()
    wb.open()
    print("Board info:", read_ident(wb))

    m, s = pty.openpty()
    tty = os.ttyname(s)
    print("LiteX Crossover UART created: {}".format(tty))

    stop_event = threading.Event()
    threads = [
        threading.Thread(target=pty2crossover, args=[wb, m, stop_event], daemon=True),
        threading.Thread(target=crossover2pty, args=[wb, m, stop_event], daemon=True),
    ]
    for thread in threads:
        thread.start()

    baudrate = int(float(args.baudrate))
    timout = 30
    #print('Using serial backend: {} with baudrate {}'.format(args.term,baudrate))
    print("Attempting to open:"+str(tty)+" at baud "+str(baudrate)+
            " with timeout=" + str(timout))

    try:
        serial_fd = Serial(tty, baudrate=baudrate, timeout=timout)
    except (Exception) as error:
        # SerialException if device cannot be found or properly configured
        # ValueError if values are incorrect
        print("Failed to open:"+str(tty)+" ("+str(type(error))+":"+str(error)+")")
        return None
    print("Serial port "+tty+" open")
    '''

    # Set up logger settings
    log_dir = Path(".")
    if args.log_dir:
        log_dir = Path(args.log_dir)

    log_filename = create_base_filename_identifier("DDR4")
    log_filepath = create_log_path("LOG",log_filename, log_dir)
    if not log_filepath:
        # Can't create log file
        return 1

    print("Base filename:", log_filepath)
    logger = setup_logger(log_filepath,print_stdout = True)

    # Create UART stdout
    uart_log_filename = create_log_path("UART",log_filename, log_dir)
    # Create UART log file
    uart_log_file = open(uart_log_filename,"w")


    experiment = build_experiment(args,logger,single_step = False)
    experiment.filebasename = log_filename
    experiment.log_dir = log_dir
    experiment.uart_log_file = uart_log_file
    experiment.start()

    '''
    
    # open terminal and run pexpect

    # Write the value 0xa5a5a5a5 as a 32 bit word to 0x10000000 word locations
    # Takes about 90 seconds
    #mem_write 0x40000000 0xa5a5a5a5 0x10000000 4

    # Compare memory (takes about 2 minutes): perhaps break this up a bit so we don't have 
    #  the UART full with all the differences when there is a failure
    #mem_cmp 0x40000000 0x60000000 0x08000000
    #

    stop_event.set()
    for thread in threads:
        thread.join(timeout=0.05)

    wb.close()
    '''

if __name__ == "__main__":
    main()

