#!/usr/bin/env python3

    # we are li
import time
import random
import argparse
import sys
from pathlib import Path
import logging
from subprocess import run


from datetime import datetime

from rowhammer_tester.scripts.utils import RemoteClient, litex_server, hw_memset, hw_memtest, get_litedram_settings, read_ident

DEFAULT_PATTERN = 0xa5a5a5a5
# Format string for printing the date and time
TIME_STRING_FORMAT = "%Y-%m-%d %H:%M:%S"

def create_base_filename_identifier(prefix):
    ''' Create a base filename used for all files generated by this experiment '''
    current_date_time = datetime.now().strftime("%B_%d_%Y__%H_%M_%S")
    # Add CTRL as the prefix to specify it is a DDR controller test
    #  (the bistream is not enough - the same bitstream may be used for the DDR test)
    return str(prefix + "_" + current_date_time+".log")

def setup_logger(log_filename:str, include_level = True, print_stdout = False):
    ''' Static method for creating custom loggers '''
    if include_level:
        formatter = logging.Formatter('[%(asctime)s] %(levelname)-8s %(message)s', datefmt=TIME_STRING_FORMAT)
    else:
        formatter = logging.Formatter('[%(asctime)s] %(message)s', datefmt=TIME_STRING_FORMAT)
    try:
        handler = logging.FileHandler(log_filename)
    except (FileNotFoundError) as error:
        print("Logging File "+log_filename+"cannot be opened")
        return None

    handler.setFormatter(formatter)
    logger = logging.getLogger("main_log")
    logger.setLevel(logging.INFO)
    logger.addHandler(handler)

    if print_stdout:
        consoleHandler = logging.StreamHandler(sys.stdout)
        consoleHandler.setFormatter(formatter)
        logger.addHandler(consoleHandler)

    return logger

def initial_experiment_logging(logger,args):
    ''' Logs information at the start of the execution (shared with multiple experiments) '''
    # Print information about the current version of the code (what is committed)
    logger.info("git commit information")
    # Get the commit tag
    p = run( [ 'git', 'show', '--oneline', '-s' ], capture_output=True )
    out = p.stdout.decode().strip()
    logger.info("\tgit commit:"+out)
    # Get the commit information (message and date)
    p = run( [ 'git', 'log', '-1', '--format=%cd', '--date=local' ], capture_output=True )
    out = p.stdout.decode().strip()
    logger.info("\tgit commit date:"+out)
    # Get the current git status (to see if something hadn't been committed)
    p = run( [ 'git', 'status', '--porcelain', ], capture_output=True )
    lines =  p.stdout.decode().strip()
    print(lines)
    if lines and len(lines) > 0:
        logger.info("\tgit status:"+out)
        lines = lines.splitlines()
        for line in lines:
            logger.info("\t\t"+line.strip())

    # Print the value of all the options when the executable was run
    logger.info("Command line information")
    logger.info("\tCommand line:"+str(sys.argv))
    dict_args = vars(args)
    for arg in dict_args:
        logger.info("\targ:"+arg+"="+str(dict_args[arg]))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    #parser.add_argument('--srv', action='store_true')
    parser.add_argument('--dbg', action='store_true')
    parser.add_argument('--pattern', help="Pattern to use (hex, i.e., 0xFFFFFFFF)", type=str)
    parser.add_argument('--continuous', action='store_true')
    parser.add_argument('--iterations', type=int)
    parser.add_argument("--log_dir", help="Directory to store log files", type=str)
    #parser.add_argument('--test-modules', action='store_true')
    #parser.add_argument('--test-memory', action='store_true')
    args = parser.parse_args()

    log_filename = create_base_filename_identifier("DDR4")
    log_dir = Path(".")
    if args.log_dir:
        log_dir = Path(args.log_dir)
    filepath = Path(log_dir, log_filename)

    print("Logfilename:"+str(filepath))
    logger = setup_logger(filepath,print_stdout = True)
    initial_experiment_logging(logger,args)
    
    #if args.srv:
    #    litex_server()

    wb = RemoteClient()
    wb.open()
    print("Board info:", read_ident(wb))

    mem_base = wb.mems.main_ram.base
    mem_range = wb.mems.main_ram.size  # bytes

    # we are limited to multiples of DMA data width
    settings = get_litedram_settings()
    dma_data_width = settings.phy.dfi_databits * settings.phy.nphases
    nbytes = dma_data_width // 8

    # pattern
    p = DEFAULT_PATTERN
    if args.pattern:
        p = int(args.pattern,16)
    print(f"Pattern=0x{p:08X}")

    # Set pattern
    print("Writing pattern")
    hw_memset(wb, 0x0, mem_range, [p], args.dbg)

    print("Starting read test")

    if args.continuous:
        iterations = sys.maxsize
    elif args.iterations:
        iterations = args.iterations
    else:
        iterations = 10

    total_errors = 0
    for i in range(iterations):
        logger.info(f"Iteration {i+1} ({total_errors} errors)")
        errors = hw_memtest(wb, 0x0, mem_range, [p], args.dbg)
        if len(errors) > 0:
            logger.info('!!! Failed pattern: {:08x} !!!'.format(p))
            for e in errors:
                logger.info(
                    'Failed: 0x{:08x} == 0x{:08x}'.format(
                        mem_base + e.offset * nbytes, wb.read(mem_base + e.offset * nbytes)))
                logger.info('  data     = 0x{:x}'.format(e.data))
                logger.info('  expected = 0x{:x}'.format(e.expected))
        #else:
        #    logger.info("Test pattern OK!")

    wb.close()
